/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg:           'var(--color-bg)',
        'bg-dark':    'var(--color-bg-dark)',
        text:         'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        gold:         'var(--color-gold)',
        'gold-light': 'var(--color-gold-light)',
        ivory:        'var(--color-ivory)',
        border:       'var(--color-border)',
        "surface-container-high": "#ece7e7",
        "on-secondary-fixed-variant": "#574500",
        "on-tertiary-container": "#a17f3b",
        "inverse-surface": "#313030",
        "surface": "#fdf8f8",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#e9c349",
        "on-surface-variant": "#444748",
        "on-error": "#ffffff",
        "tertiary": "#000000",
        "surface-container-low": "#f7f2f2",
        "secondary-fixed": "#ffe088",
        "primary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed-variant": "#5d4201",
        "on-primary-fixed": "#1c1b1b",
        "muted-sand": "#f0ede9",
        "ink-charcoal": "#1a1a1a",
        "primary-fixed": "#e5e2e1",
        "background": "#fdf8f8",
        "on-background": "#1c1b1c",
        "surface-dim": "#ddd9d9",
        "error-container": "#ffdad6",
        "secondary-container": "#fed65b",
        "inverse-on-surface": "#f4f0f0",
        "primary": "#000000",
        "secondary": "#735c00",
        "tertiary-container": "#261900",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#e9c176",
        "inverse-primary": "#c8c6c5",
        "surface-tint": "#5f5e5e",
        "surface-variant": "#e6e1e1",
        "on-secondary-container": "#745c00",
        "outline-variant": "#c4c7c7",
        "surface-container": "#f1eded",
        "surface-container-lowest": "#ffffff",
        "burnished-gold": "#d4af37",
        "luxury-gold": "#BFA46F",
        "champagne": "#F7E7CE",
        "warm-ivory": "#FAF8F5",
        "surface-bright": "#fdf8f8",
        "primary-container": "#1c1b1b",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#474746",
        "on-primary": "#ffffff",
        "on-primary-container": "#858383",
        "outline": "#747878",
        "surface-container-highest": "#e6e1e1",
        "surface-cream": "#fdf8f8",
        "on-tertiary-fixed": "#261900",
        "on-surface": "#1c1b1c",
        "on-secondary-fixed": "#241a00",
        "tertiary-fixed": "#ffdea5",
        "heritage-navy": "#1a2a3a",
        "dark-surface": "#161414",
        "dark-surface-container": "#211f1f",
        "dark-muted-sand": "#2a2726",
        "dark-on-surface-variant": "#c4c0bd",
        "champagne-gold": "#d4af37",
        "porcelain-white": "#ffffff",
        "bone-gray": "#f0ede9"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "section-gap": "120px",
        "margin-desktop": "64px",
        "container-max": "1440px",
        "unit": "8px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "site-x": "64px",
        "site-x-sm": "20px"
      },
      maxWidth: {
        "site": "1440px",
      },
      fontFamily: {
        serif: ["var(--font-playfair)", "Georgia", "serif"],
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        cormorant: ["var(--font-cormorant)", "Georgia", "serif"],
        "display-lg": ["var(--font-playfair)", "Playfair Display", "serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "price-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-playfair)", "Playfair Display", "serif"],
        "headline-md": ["var(--font-playfair)", "Playfair Display", "serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"]
      },
      fontSize: {
        "hero-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "hero-md": ["52px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "hero-sm": ["40px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "section-lg": ["42px", {"lineHeight": "1.2", "fontWeight": "400"}],
        "section-sm": ["32px", {"lineHeight": "1.2", "fontWeight": "400"}],
        "collection-lg": ["30px", {"lineHeight": "1.3", "fontWeight": "400"}],
        "collection-sm": ["24px", {"lineHeight": "1.3", "fontWeight": "400"}],
        "nav-lg": ["14px", {"lineHeight": "1.0", "letterSpacing": "0.08em", "fontWeight": "500"}],
        "nav-sm": ["13px", {"lineHeight": "1.0", "letterSpacing": "0.08em", "fontWeight": "500"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "price-lg": ["20px", {"lineHeight": "1.0", "fontWeight": "500"}],
        "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      },
      animation: {
        marquee: 'marquee 22s linear infinite',
        'fade-in-up': 'fade-in-up 1.2s cubic-bezier(0.21, 0.47, 0.32, 0.98) 0.5s both',
      },
      keyframes: {
        marquee: {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        }
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
  ],
};
