/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg:           'var(--color-bg)',
        'bg-dark':    'var(--color-bg-dark)',
        text:         'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        gold:         'var(--color-gold)',
        'gold-light': 'var(--color-gold-light)',
        ivory:        'var(--color-ivory)',
        border:       'var(--color-border)',
        "on-tertiary-fixed": "#291803",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "primary": "#041525",
        "surface-tint": "#506072",
        "surface-container-highest": "#e5e2dd",
        "on-tertiary-container": "#a88b6b",
        "obsidian": "#1A1A1A",
        "primary-container": "#1a2a3a",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "secondary": "#735c00",
        "outline": "#74777d",
        "surface": "#fcf9f4",
        "champagne-gold": "#D4AF37",
        "on-secondary-container": "#745c00",
        "heritage-navy": "#1A2A3A",
        "porcelain-white": "#FCF9F4",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffddb9",
        "inverse-on-surface": "#f3f0eb",
        "surface-container": "#f0ede9",
        "inverse-primary": "#b7c8dd",
        "surface-variant": "#e5e2dd",
        "surface-container-low": "#f6f3ee",
        "on-primary-fixed": "#0c1d2c",
        "on-primary-container": "#8191a5",
        "on-background": "#1c1c19",
        "tertiary-container": "#38250d",
        "on-secondary-fixed": "#241a00",
        "inverse-surface": "#31302d",
        "primary-fixed-dim": "#b7c8dd",
        "secondary-container": "#fed65b",
        "on-primary-fixed-variant": "#384859",
        "surface-dim": "#dcdad5",
        "on-surface-variant": "#44474c",
        "tertiary-fixed-dim": "#e2c19e",
        "bone-gray": "#E5E4E2",
        "on-secondary-fixed-variant": "#574500",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d3e4fa",
        "on-tertiary-fixed-variant": "#594328",
        "tertiary": "#211100",
        "surface-container-high": "#ebe8e3",
        "error-container": "#ffdad6",
        "surface-bright": "#fcf9f4",
        "on-surface": "#1c1c19",
        "secondary-fixed": "#ffe088",
        "background": "#fcf9f4",
        "outline-variant": "#c4c6cc",
        "secondary-fixed-dim": "#e9c349"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-lg": "48px",
        "margin-tablet": "32px",
        "margin-mobile": "20px",
        "stack-xl": "80px",
        "stack-md": "24px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        serif: ['var(--font-cormorant)', 'Cormorant Garamond', 'Georgia', 'serif'],
        sans:  ['var(--font-dm-sans)',   'DM Sans',            'system-ui', 'sans-serif'],
        "display-lg": ["var(--font-playfair)", "Playfair Display", "serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "price-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-playfair)", "Playfair Display", "serif"],
        "headline-md": ["var(--font-playfair)", "Playfair Display", "serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "price-lg": ["20px", {"lineHeight": "1.0", "fontWeight": "500"}],
        "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      },
      animation: {
        marquee: 'marquee 22s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
  ],
};
